#!/usr/bin/perl -w

use esmith::Build::CreateLinks  qw(:all);

my $event = 'nethserver-automysqlbackup-update';
event_actions($event,
'initialize-default-databases' => '00',
'automysqlbackup.conf'=>'01',
'automysqlbackup-mysql.conf'=>'02',
'automysqlbackup-rh-mariadb101.conf'=>'02',
'automysqlbackup-rh-mariadb102.conf'=>'02',
'automysqlbackup-rh-mariadb103.conf'=>'02');

templates2events("/etc/cron.d/runmysqlbackup", $event);

$event = 'nethserver-rh-mariadb101-update';
event_actions($event,
'automysqlbackup-rh-mariadb101.conf'=>'95');
templates2events("/etc/cron.d/runmysqlbackup", $event);

$event = 'nethserver-rh-mariadb102-update';
event_actions($event,
'automysqlbackup-rh-mariadb102.conf'=>'95');
templates2events("/etc/cron.d/runmysqlbackup", $event);

$event = 'nethserver-rh-mariadb103-update';
event_actions($event,
'automysqlbackup-rh-mariadb103.conf'=>'95');
templates2events("/etc/cron.d/runmysqlbackup", $event);
